@baseUrl = http://localhost:4000

@urlPath = api/v1

###
POST {{{baseUrl}}/{{urlPath}}/signup}
Content-Type: application/json
Accept: application/json
withCredentials: true


{
    "username": "Jahid Hossain Mridha",
    "password": "1234@Qwer",
    "email": "jahid4k@gmail.com",
    "avatarColor": "red",
    "avatarImage": "redimage"
}
